### ISSUE TITLE
[Feature request] Sort array of struct columns with sort_columns

### ISSUE THREAD

**Issue by PatrykMilewski** [mrpowers-io/quinn#109]
Hey!

I see that `sort_columns` is using `sorted(df.columns)`, which will only sort root level columns. I would like to use that to sort array of struct fields:
```
field1 array<struct<field2: string, field1: string>>
```

**Comment by kv41999** [comment]
Hi Patryk,
Just wanted some clarification. Do you want all the columns to sort along with the fields inside a struct column or do you want to explicitly give the name of the struct column that you want ordered and leave the rest of the columns unordered?

**Comment by PatrykMilewski** [comment]
Hey!
> all the columns to sort along with the fields inside a struct column
this case

**Comment by jeffbrennan** [comment]
working on this

**Comment by MrPowers** [comment]
Thanks @jeffbrennan.  Would be cool to create an interface(s) that's similar to the Python `sort()` and `sorted()` methods.  That'd seem to be the Pythonic approach.

**Comment by MrPowers** [comment]
I was originally trying to finish this work [here](https://github.com/MrPowers/quinn/pull/48), but didn't figure it out, so going to close my PR.
