### ISSUE TITLE
Improve project governance

### ISSUE THREAD

**Issue by MrPowers** [mrpowers-io/quinn#243]
### Feature Type

- [ ] Adding new functionality to quinn

- [ ] Changing existing functionality in quinn

- [ ] Removing existing functionality in quinn

### Problem Description

Project governance should be specified.

This includes the maintainers of the project, the technical steering committee, and voting.

### Feature Description

Need to organize an informal code foundation with project governance guidance.

**Comment by SemyonSinchenko** [comment]
@MrPowers

**Comment by MrPowers** [comment]
@SemyonSinchenko - proposed next steps:

* move this repo to mrpowers-io
* follow the repo governance outlined here: https://www.mrpowers.io/governance/mrpowers-io-repos/

Let me know if that sounds alright to you!

**Comment by SemyonSinchenko** [comment]
Repository was moved
